server:
  port: 80
spring:
  datasource:
#     username: sa
#     password:
#     url: jdbc:h2:tcp://localhost/~/schedule;MODE=MYSQL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  freemarker:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss EEE
logging:
  level: info
  io:
    github: debug
