server:
  port: 80
spring:
  datasource:
#    username: root
#    password: root-mysql-yo
#  url: jdbc:mysql://172.16.8.111:3306/quartz?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&zeroDateTimeBehavior=convertToNull
     username: xgdebug
     password: F9AF624CBF5D6B8D
     url: jdbc:mysql://106.75.55.43:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&zeroDateTimeBehavior=convertToNull

#     username: sa
#     password:
#     url: jdbc:h2:tcp://localhost/~/schedule;MODE=MYSQL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  freemarker:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss EEE
logging:
  level: info
  io:
    github: debug
